baseURL = "https://winegrower.cn/"
languageCode = "zh-CN"
title = "winegrower"
theme = "winegrower"

[params]
  subtitle = "种葡萄并酿酒的人"
  description = "种葡萄并酿酒的人"
  enableOpenGraph = true
  enableTwitterCards = true
  disableDarkmode = false
  favicon = "/favicon.ico"
  startYear = "2008"
  sidebarQuote = "种葡萄并酿酒的人"
  enableReadingTime = true
  walineServer = "https://c.winegrower.cn"

  avatar = "/logo.png"
  email = "winegrower@foxmail.com"
  github = "https://github.com/YardenZhang"

  [params.author]
    name = "winegrower"
    email = "winegrower@foxmail.com"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  posts = "/posts/:slug/"
  categories = "/categories/:slug/"
  tags = "/tags/:slug/"

[[menu.main]]
  url = "/posts"
  name = "Archive"
  weight = 1

[[menu.main]]
  url = "/categories"
  name = "Categories"
  weight = 2

[[menu.main]]
  url = "/tags"
  name = "Tags"
  weight = 3

[[menu.main]]
  url = "/links"
  name = "Links"
  weight = 4

[[menu.main]]
  url = "/about/"
  name = "About"
  weight = 5
